name: Publish Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    steps:
      - name: Setup environment variables
        run: |
          echo "REPO_NAME=`basename ${{ github.repository }}`" >> $GITHUB_ENV
          echo "LATEST_TAG=$(curl -qsSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ env.GITHUB_TOKEN }}
          fetch: false
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          always-auth: true
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@cheatoid"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create release
        uses: actions/create-release@master
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.REPO_NAME }} ${{ github.ref_name }}
          body: "**Full Changelog**: ${{ github.event.repository.html_url }}/compare/${{ env.LATEST_TAG }}...${{ github.ref_name }}\n---\n${{ steps.changelog.outputs.changelog }}"
          draft: false
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
      - name: Publish package
        run: npm publish --access public
