name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          always-auth: true
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@cheatoid"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish package
        run: npm publish --access public
